---
version: '2'
networks:
  cluster:
    driver: bridge
services:
  zookeeper:
    build: .
    image: sj_zookeeper_img
    command: zookeeper
    ports:
      - 2181:2181
    networks:
      - cluster
  kafka_1:
    build: .
    image: sj_kafka_img
    environment:
      kafka_port: 9092
      kafka_id: 1
      kafka_ip: 10.8.0.14
    hostname: kafka_1
    ports:
      - 9092:9092
    networks:
      - cluster
    links:
      - zookeeper:zookeeper
  kafka_2:
    build: .
    image: sj_kafka_img
    environment:
      kafka_port: 9092
      kafka_id: 2
      kafka_ip: 10.8.0.14
    hostname: kafka_2
    ports:
      - 9093:9092
    networks:
      - cluster
    links:
      - zookeeper:zookeeper
  kafka_3:
    build: .
    image: sj_kafka_img
    environment:
      kafka_port: 9092
      kafka_id: 3
      kafka_ip: 10.8.0.14
    hostname: kafka_3
    ports:
      - 9094:9092
    networks:
      - cluster
    links:
      - zookeeper:zookeeper
